### ISSUE TITLE
Hide extraneous context menu options (e.g. Reveal in Tree View)

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#354]
There are quite a few extraneous options listed in the context menu around different components of settings view:

![screenshot 2015-01-27 10 33 34](https://cloud.githubusercontent.com/assets/823545/5921188/3fa02f0e-a610-11e4-93c1-80703fc5a7bc.png)
Reveal in Tree View kind of doesn't make sense here – what would it even be revealing?

![image](https://cloud.githubusercontent.com/assets/823545/5921262/b8d6b384-a610-11e4-8182-53a20c657ee6.png)
None of the entries in the last section (that I'm guessing are coming from the mini-editor) really make sense in the context of settings-view inputs.

- [x] Remove Reveal in Tree View atom/tree-view#406
- [x] Remove mini editor menu entries
  - [x] Remove Change Encoding atom/encoding-selector#21
  - [x] Remove Correct Spelling atom/spell-check#56
  - [x] Remove Go to Declaration atom/symbols-view#94
